// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nhom5.Data;

#nullable disable

namespace Nhom5.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230522054550_Create_Table_NhanVien")]
    partial class Create_Table_NhanVien
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("Nhom5.Models.Kho", b =>
                {
                    b.Property<string>("KhoID")
                        .HasColumnType("TEXT");

                    b.Property<string>("DiaChiKho")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TenKho")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TenSanPham")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ThuongHieu")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("KhoID");

                    b.ToTable("Khos");
                });

            modelBuilder.Entity("Nhom5.Models.NhanVien", b =>
                {
                    b.Property<string>("IDNhanVien")
                        .HasColumnType("TEXT");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("KinhNghiem")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TenNhanVien")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tuoi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IDNhanVien");

                    b.ToTable("NhanVien");
                });
#pragma warning restore 612, 618
        }
    }
}
